Script to make AC grid for Marmion

```{r setup}
# knitr options
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = FALSE, fig.align = 'center', fig.width = 10, fig.height = 7) 

# libraries 
library(tidyverse)
library(dplyr)
library(ggplot2)
library(sp)
library(raster)
library(rgeos)
library(rgdal)
library(sf)
library(lwgeom)
library(googledrive)
library(units)
library(nngeo)
library(magrittr)
library(todor)
library(smoothr)

# data
# sites <- st_read("./data/gpkg/ac_grid_4283.gpkg") 
BR <- st_read("./data/gpkg/BR_4283.gpkg") # boat ramps
BRtrips <- readRDS("./data/gpkg/2.1_BRtrips.gpkg")
npz <- readRDS("./data/gpkg/2.1_acNPZ_4283.gpkg")
# comm <- st_read("./data/gpkg/commwater.gpkg")
# state <- st_read("./data/gpkg/statewater.gpkg")
grid_base <- st_read("./data/gpkg/mar_acBase.gpkg")

water <- readRDS("./data/gpkg/2.1_acStudySite_4283.gpkg")

dat <- read_csv("data/01_data/1.2_dat.csv") %>% 
  filter(ActivityType == "Extractive") %>%
  filter(!is.na(UseLat), !is.na(UseLong)) %>% 
  st_as_sf(coords = c("UseLong", "UseLat"), crs = 4283)


# functions
source("./functions/spatialFunc.R") # spatial functions
source("./functions/ascFunc.R")

sf_use_s2(FALSE)

# testing layers
# ggplot() +
#   geom_sf(data = state) +
#   geom_sf(data = comm, fill = 'red') +
#   geom_sf(data = sim) +
#   geom_sf(data = npz, fill = 'blue') +
#   geom_sf(data = BR)
#   
# defualt figure
  ax.title <- 14
  ax.text <- 9
  ax.legend <- 12
  strip <- 9
  a4_width <- 160
  my_theme <- theme_classic() + theme( axis.text = element_text(size = ax.text),
                                    text = element_text(size = ax.text),
                                    axis.title = element_text(size = ax.title),
                                    line = element_line(size = 0.3),
                                    strip.background = element_rect(colour = "white", fill =
                                                                      "gray80"),
                                    strip.text = element_text(size = strip))

 col <- c("#d38685") 
```

```{r}
# sim_name <- "simog"
# sim <- st_read("./data/gpkg/sim_og.gpkg")

# sim_name <- "sim1"
# sim <- st_read("./data/gpkg/sim1.gpkg")
# 
# # sim_name <- "sim2"
# sim <- st_read("./data/gpkg/sim2.gpkg")
# 
# # sim_name <- "sim3"
# sim <- st_read("./data/gpkg/sim3.gpkg")
# 
# # sim_name <- "sim4"
# sim <- st_read("./data/gpkg/sim4.gpkg")

## split
sim_name <- "simog_split"
sim <- st_read("./data/gpkg/simog_split.gpkg")
# 
# sim_name <- "sim1_split"
# sim <- st_read("./data/gpkg/sim1_split.gpkg")

# sim_name <- "sim2_split"
# sim <- st_read("./data/gpkg/sim2_split.gpkg")
# 
# # sim_name <- "sim3_split"
# sim <- st_read("./data/gpkg/sim3_split.gpkg")
# 
# sim_name <- "sim4_split"
# sim <- st_read("./data/gpkg/sim4_split.gpkg")
```


# Make choice set
```{r}
grid <- ASCgrid(poly = grid_base, sz_current = npz, sz_sim = sim, point = dat, from = 0.03, by = 0.02, min_area = 0, crs = 4283, vert = FALSE) # crs using degrees
```

##########################

# Attributes
```{r}
site_centroid <- st_centroid_within_poly(grid) # gets centroid of every grid cell
grid$site_centroid <- site_centroid$geom # appending centroid

# getting distance from each boat rampe to the centroid of the sites
BR <- st_transform(BR, crs(grid))
dist <- as.data.frame(set_units(st_distance(grid$site_centroid, BR), km)) 
names(dist) <- unique(BR$RampID)
gridID_alt <- grid$gridID_alt
dist$gridID_alt <- gridID_alt
dist <- dist %>% gather("BR", "site.centroid_km.BR", 1:length(dist) - 1) 
grid <- grid %>% left_join(dist, by = "gridID_alt") # join 

grid <- grid |> st_sf() |> # wont work without st_sf()
  dplyr::select(-site_centroid) 

gridID_vis <- grid %>% 
  dplyr::select(gridID_alt, geom) %>% 
  distinct() 

st_write(gridID_vis, 
         paste0("./data/gpkg/2.1_acChoiceSetQ", sim_name, "_4283.gpkg"), 
         append = FALSE) # need to write with st_write to open in QGISRUMs

# check 
# ggplot() +
#   geom_sf(data = sites$geom, aes(fill = sites$SZ)) +
#   geom_sf(data = sites$site_centroid, color = 'red')
```

```{r}
# Use spatial points
dat <- st_crop(dat, grid) # removing outliers

# need one trip per row (longest site visited on trip)
dat <- dat %>% 
  group_by(PersonID, TripID) %>% 
  slice(which.max(decDuration)) %>% 
  ungroup()
# which(duplicated(dat$TripID) == TRUE) # Should be none

# allocating sites to grids
dat <- dat %>%
  st_join(gridID_vis, left = T, join = st_intersects)

# selecting attributes, and tidying
dat <- dat %>% 
  rename(gridID_vis = gridID_alt) %>% 
  dplyr::select(TripID, PersonID, gridID_vis, Site) %>% 
  distinct() %>% 
  mutate(BR = ifelse(Site %in% "Hillarys", "104", NA),
         BR = ifelse(Site %in% "Mindarie", "105", BR),
         BR = ifelse(Site %in% "OceanReef", "106", BR),
         BR = ifelse(Site %in% "TwoRocks", "112", BR)) %>% 
  # mutate(UseLong = st_coordinates(.)[,1]) %>% 
  # mutate(UseLat = st_coordinates(.)[,2]) %>% 
  dplyr::select(-Site) %>% 
  as.data.frame()

# which(is.na(dat$gridID_vis)==TRUE)

# this chunk should give you a data set with one trip per row, with a few trip/fisher attributes and the ID of visited grids 
```

# Join data
```{r join}
og_dat <- dat # copying original data test join

dat <- inner_join(dat, grid, by = "BR") # FALSE

# testing join
a <- as.data.frame(table(og_dat$BR)) %>% rename(launches = Freq)
b <- as.data.frame(table(grid$BR)) %>%  rename(n_sites = Freq)
c <- left_join(a, b)
c$times <- c$launches*c$n_sites
test = sum(c$times)
test == nrow(dat) # this should be TRUE
```

# Getting distance from BR to mean coordinate of all uses that launched from teh same boat ramp
```{r}
dat <- dat %>% 
  st_as_sf() # turn to sf object

# get centroid of use points
tmp <- dat %>%
  group_by(gridID_vis, BR) %>%
  summarise(use_centroid = st_union(geometry)) %>%
  st_centroid() %>%
  ungroup() %>%
  mutate(id = row_number())

# making distance data frame
dist <- as.data.frame(set_units(st_distance(tmp, BR), km)) # distance from use centroid to each BR
names(dist) <- unique(BR$RampID) 
dist$gridID_vis <- tmp$gridID_vis 
dist$BR <- tmp$BR 
dist$id <- tmp$id 
len <- length(dist) - 3 
dist <- dist %>% gather("BRdist", "use.centroid_km.BR", 1:len) # gather
dist$use.centroid_km.BR <- as.numeric(dist$use.centroid_km.BR) 

dist <- dist %>% 
  filter(BR == BRdist) %>% 
  dplyr::select(gridID_vis, BR, use.centroid_km.BR) %>% 
  rename(gridID_alt = gridID_vis) # got to join to alt not visited

dat <- as.data.frame(dat)

dat <- left_join(dat, dist, by = c("BR", "gridID_alt")) # join

dat <- dat %>% 
  mutate(site.centroid_km.BR = as.numeric(site.centroid_km.BR)) %>% 
  mutate(km_BR = ifelse(is.na(use.centroid_km.BR), site.centroid_km.BR, use.centroid_km.BR)) # distance tc to be measured from
```

# Choice and travel cost ($0.54/km)
```{r choice and travel cost}
dat <- dat %>% 
  # mutate(centroidLong = st_coordinates(polyCentroid)[,1]) %>% # need this is using dynamic variables
  # mutate(centroidLat = st_coordinates(polyCentroid)[,2]) %>%
  mutate(choice = ifelse(gridID_vis == gridID_alt, 1, 0)) %>% 
  mutate(travelCost = as.numeric(0.54*km_BR)) %>% 
  dplyr::select(-c(geometry, site.centroid_km.BR, use.centroid_km.BR))
```

# filtering out current sz and sim sz with no value
```{r}
dat_rum <- dat %>% 
  filter(sz_current != 1, sz_wo_value != 1)

sz_to_remove <- dat_rum %>% 
  dplyr::select(num_range("sz", 1:10)) %>% 
  summarise_all(sum) 

sz_to_remove <- names(sz_to_remove[, which(sz_to_remove %in% 0)])
 
dat_rum_sf <- dat_rum %>% dplyr::select(-c(sz_to_remove))
dat_rum_df <- dat_rum %>% dplyr::select(-c(sz_to_remove, sz_current, sz_wo_value, geom))

sz_w_value_plot <- ggplot() +
  geom_sf(data = grid$geom, aes(fill = as.factor(grid$sz_w_value)), lwd = 0.25) +
  xlab("Longitude") + ylab("Latitude") +
  labs(fill = "Value") +
#   geom_sf(data = dat$geom, size = 0.5) +
  my_theme +
  ggtitle("SZ with value")

sz_wo_value_plot <- ggplot() +
  geom_sf(data = grid$geom, aes(fill = as.factor(grid$sz_wo_value)), lwd = 0.25) +
  xlab("Longitude") + ylab("Latitude") +
  labs(fill = "Value") +
#   geom_sf(data = dat, size = 0.5) +
  my_theme +
  ggtitle("SZ without value")

sz_wo_value_plot
```


# Save output
```{r save}
# plot
ggsave(sz_w_value_plot, path = "./plots/ASC RUM", filename = paste("acSZwValue_", sim_name, ".png", sep = ''), width = 4, height = 4)

ggsave(sz_wo_value_plot, path = "./plots/ASC RUM", filename = paste("acSZwoValue_", sim_name, ".png", sep = ''), width = 4, height = 4)

# gpkg
saveRDS(dat, paste0("./data/gpkg/2.1_acChoiceSet_",sim_name ,"4283.gpkg"))
saveRDS(dat_rum_sf, paste0("./data/gpkg/2.1_acChoiceSet_rum", sim_name,"_4283.gpkg")) # sz with no values filtered - for 3.1

# csv
write_csv(dat, paste0("./data/02_data/2.1_ac", sim_name,".csv"))
write_csv(dat_rum_df, paste0("./data/02_data/2.1_ac", sim_name,"_rum.csv")) # sz with no values filters - for stata
```